version: "3.8"
services:
  weather-island-redis:
    container_name: weather-island-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: zlcls456/weather-island-redis
    ports:
      - "6380:6379"
  weather-island-app:
    container_name: weather-island-app
    build: .
    depends_on:
      - weather-island-redis
    image: zlcls456/weather-island-app
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - TEAM_ID=${TEAM_ID}
      - APNS_APP_ID=${APNS_APP_ID}
      - APNS_KEY_ID=${APNS_KEY_ID}
      - WEATHER_KIT_KEY_ID=${WEATHER_KIT_KEY_ID}
      - WEATHER_KIT_SERVICE_ID=${WEATHER_KIT_SERVICE_ID}
    ports:
      - "8081:8080"
    restart: always