server:
  port: 8081

spring:
  data:
    redis:
      host: host.docker.internal
      port: 6380

weather:
  search:
    scheduler:
      period: 10
      time-unit: MINUTES

apple:
  team-id: ${TEAM_ID}
  app-id: ${APP_ID}
  service-id: ${SERVICE_ID}
  push:
    notification:
      key-id: ${APNS_KEY_ID}
  weather:
    kit:
      key-id: ${WEATHER_KIT_KEY_ID}



logging:
  level:
    project.app.apns_server.modules : info