spring:
  data:
    redis:
      host: localhost
      port: 6379

weather:
  search:
    scheduler:
      period: 1
      time-unit: MINUTES

apple:
  team-id: ${TEAM_ID}
  app-id: ${APP_ID}
  push:
    notification:
      key-id: ${APNS_KEY_ID}

logging:
  level:
    project.app.apns_server.modules : debug