spring:
  data:
    redis:
      host: localhost
      port: 6379

open-weather:
  api:
    key: ${OPEN_WEATHER_API_KEY}

weather:
  search:
    scheduler:
      period: 30
      time-unit: SECONDS

apple:
  push:
    notification:
      app-bundle-id: ${APP_BUNDLE_ID}
      auth-key-id: ${AUTH_KEY_ID}
      team-id: ${TEAM_ID}

logging:
  level:
    project.app.apns_server.modules : debug