spring:
  data:
    redis:
      host: host.docker.internal
      port: 6380

open-weather:
    api:
      key: ${OPEN_WEATHER_API_KEY}

weather:
  search:
    scheduler:
      period: 30
      time-unit: MINUTES

apple:
  push:
    notification:
      app-bundle-id: ${APP_BUNDLE_ID}
      key-file: ${APNS_KEY_FILE}
      auth-key-id: ${AUTH_KEY_ID}
      team-id: ${TEAM_ID}

logging:
  level:
    project.app.apns_server.modules : debug